version: "3.9"
services:
  kwirk-db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    container_name: kwirk-mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d
#  kwirk-app:
#    platform: "linux/amd64"
#    container_name: kwirk-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        NEXT_PUBLIC_CLIENTVAR: "clientvar"
#        # image: t3-app
#    depends_on:
#      - kwirk-db
#    working_dir: /app
#    ports:
#      - 3001:3001
#    environment:
#      - DATABASE_URL=${DATABASE_URL}
#      - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
#      - NEXT_PUBLIC_UPLOADTHING_SECRET=${NEXT_PUBLIC_UPLOADTHING_SECRET}
#      - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
#      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
#      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # - NODE_ENV= tofill
  #   develop:
  #     watch:
  #       - path: ./app/package.json
  #         action: rebuild
  #       - path: ./app
  #         target: /usr/src/app
  #         action: sync
